### ISSUE TITLE
how to generate old type fonts

### ISSUE THREAD

**Issue by lattice26** [DocCreator/DocCreator#11]
Thank you for your greate job,
* DocCreatorMakeFont that allows to create DocCreator old-fonts from existing (TrueType) fonts. You can save the produced files in data/font to use these fonts in DocCreator.

I found this description on README, did it means we can produce old fonts from TrueType fonts automaticallly?

**Comment by BorisMansencal** [comment]
The fonts in DocCreator (that we call "old-fonts") are "bitmap" fonts. Each character is associated with one or more images of this character. The character is not drawn from curves as in a TrueType font. Having different images for a given character allows us to reproduce the diversity of characters found in old documents.

There is a tool directly in DocCreator to manually extract such a new "old-font" from a document image. It allows to have several images for each character.
There is also an independent tool, DocCreatorMakeFont, that allows to produce an "old-font" for use in DocCreator from an (installed) TrueType font. However, this "old-font" will only have one image for each character. You will need to configure DocCreator with -DBUILD_OTHER_PROGS=ON to build such a tool.

Tell us if you need help.

**Comment by OttomanZ** [comment]
@BorisMansencal I'm using the windows executable is there is why I can do this as well?

**Comment by BorisMansencal** [comment]
@OttomanZ the windows packaged version available from https://doc-creator.labri.fr/ does not include DocCreatorMakeFont.
You would have to build from source to also build this executable.
(I will try to make available a windows packaged version from the current development branch in the coming days/weeks...)

**Comment by OttomanZ** [comment]
@BorisMansencal Thanks for the quick reply and support, it's really helpful. So for now you suggest using a Linux Install for using TTF fonts? Because I've been thinking once, I'm able to set this up on my end with your help I'd create a Youtube Tutorial Documentation for this tool as well.

**Comment by BorisMansencal** [comment]
@OttomanZ  I suggest building the development branch (pybind11) from source. It should work on Linux, Mac & Windows. But, if you are familiar with Linux, it may be easier to build on Linux (on Ubuntu for example). I can help with that.
If you create any documentation (Youtube or otherwise), it will be very welcome.
