### ISSUE TITLE
create mesh file

### ISSUE THREAD

**Issue by minouei-kl** [DocCreator/DocCreator#12]
Hi,
thank you for this great tool.
is there a documentation on how to create mesh files? currently, there are 17 brs files in the repository how can we generate more?

**Comment by BorisMansencal** [comment]
Hi,

For the 3D meshes, you can use any 3D mesh with parameterization, that is, with texture coordinates, in .obj format.
.brs is just a more compressed (custom) way to store an .obj file.
So if you can create a 3D mesh, with a mesh editor (for example with Blender or Meshlab) or programmatically (for example with the VCG library used by Meshlab), compute the texture coordinates to map the document image to the mesh, and save as .obj, you should be able to use it in DocCreator.

DocCreator provides a way to compute the texture coordinates, but it will only work if your 3D mesh is relatively planar.
14 out of the 17 meshes available in DocCreator (Vesale*.brs and livre*.brs) were obtained with a 3D scanner from real books, then parameterized this way.

If you configure/build DocCreator with -DBUILD_OTHER_PROGS_3D=ON, you will have a tool (tools/convertBRSOBJ) to convert a file from .obj format to .brs format.

Besides, in the "pybind11" branch, DocCreator also offers a 2D "warp" effect, called "elastic deformation". It allows to have a quite similar effect without the need of a 3D Mesh. It also allows to pass bounding boxes (of words for example) and get back the bounding boxes transformed by the effect. See https://github.com/DocCreator/DocCreator/blob/pybind11/framework/src/Degradations/ElasticDeformation.hpp 

Boris.
