### ISSUE TITLE
Call DocCreator with Command Line Arguments

### ISSUE THREAD

**Issue by philippgrafendorfe** [DocCreator/DocCreator#6]
Hi,

I installed the DocCreator via the installer from the website and I can process images and noise them. Now I want to access the features via command line to integrate the noise process into my workflow. Is this somehow possible?

**Comment by BorisMansencal** [comment]
Hi,
(Sorry for the delay, we are on vacation...)

On which platform are you using DocCreator ? 

With the current packaged versions (for macOS and Windows), only the GUI is available. (You can still process images by batches, using the little black factory icon in the toolbar. But it is maybe what you already did...)

With the current GitHub code, a command line tool, DocCreatorDegradator, is available. It allows to apply the various degradation effects to a given images directory. You will need to compile DocCreator from sources (and thus previously install Qt, cmake and OpenCV). You will also have to configure cmake with the option -DBUILD_OTHER_PROGS=ON and do "make install".

We plan to provide a python binding to the various degradation effects. But probably not before the end of the year...    

Boris.

**Comment by philippgrafendorfe** [comment]
Hi,

thanks for your answer. I work on windows. You are right, I already used the black factory icon. Maybe the Degredator is enough as I only want to introduce random noise to given images. 
Hopefully I will have finished my master thesis by the november. So the python binding will not help me for that. But maybe for different tasks.

Great work you did with the doccreator!

**Comment by philippgrafendorfe** [comment]
> Hi,
> (Sorry for the delay, we are on vacation...)
> 
> On which platform are you using DocCreator ?
> 
> With the current packaged versions (for macOS and Windows), only the GUI is available. (You can still process images by batches, using the little black factory icon in the toolbar. But it is maybe what you already did...)
> 
> With the current GitHub code, a command line tool, DocCreatorDegradator, is available. It allows to apply the various degradation effects to a given images directory. You will need to compile DocCreator from sources (and thus previously install Qt, cmake and OpenCV). You will also have to configure cmake with the option -DBUILD_OTHER_PROGS=ON and do "make install".
> 
> We plan to provide a python binding to the various degradation effects. But probably not before the end of the year...
> 
> Boris.

Hi Boris,

I am now going through the process to get the command line tool for degredation. There is one question coming up for me: what do you mean by "make install". The rest seems pretty clear for now.

**Comment by philippgrafendorfe** [comment]
I tried to compile doccreator according to your description for windows in the readme. This was my command:

`
cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\mingw73_64 -DCMAKE_INSTALL_PREFIX=c:\docCreator_build -DOpenCV_DIR="C:\opencv\build"
`
With this command the compiling works but I get the following message that gives me a little headache:

```
  Manually-specified variables were not used by the project:

    OpenCV_DIR
```

The degredation cannot work with openCV I guess.

**Comment by BorisMansencal** [comment]
Hi,
I have updated the README (now in markdown format and renamed README.md). Hopefully, the installation procedure will be more clear. 

Several remarks regarding your configuration command:
- OpenCV_DIR must be set beforehand and not specified as an option to the cmake configuration command. You can do this by opening a cmd prompt "CMD.exe" with Administrator privileges and do for example: `setx -m OpenCV_DIR C:\opencv\build`
- You are configuring to use "Visual Studio 15 2017 Win64" but you specify a path to Qt compiled for MinGW. I am not sure mixing the two will work. I would install a Qt version compiled with Visual Studio 15 (you have this choice if you installed Qt with the Qt Download Installer) and use that: for example with `-DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017_64`. 
(FYI, we have not tried to compile DocCreator  with MinGW yet) 
- If you want to build DocCreatorDegradator, you also have to pass: `-DBUILD_OTHER_PROGS=ON` to cmake.

If everything works correctly, it should produce a .sln file.
Then you can open this .sln file with Visual Studio.
Check that you have "Release" and "x64" for the "Solution configurations" and "Solution platforms" (comboboxes in the toolbar), then go to the menu "Build" and do "Build solution".
To install DocCreator and DocCreatorDegradator in the target directory ("c:\docCreator_build"), in the "Solution explorer" (on the right), right click on "INSTALL" in CMakeTargets and choose "Build".

You can then use DocCreatorDegradator from the command line:  
`cd c:\docCreator_build\programs`  
`DocCreatorDegradator c:\images c:\transformed_images`  
where `c:\images` contains your (original) images and `c:\transformed_images` is the output directory where produced images will be saved.

You will have to modify *software/DocCreator/src/Degradator/main.cpp* and compile and install again, if you want to change the degradation effects and/or their parameters applied to your images.

**Comment by philippgrafendorfe** [comment]
Most of your remarks where somehow clear for me from the old readme. The msvc/ming remark seems crucial. There was a 50/50 chance for me although the "msvc" should have been an obvious sign.
But anyway: unfortunately my plans are now obsolete. I wanted to implement a computational graph where a bunch of random noise is applied to a set of images, shuffled and fed directly into a neural net in a pseudo online-learning manner. But if it is necessary to compile every time for a different noise I can also go with the user interface version. It seems to be the faster and easier way although it is not that elegant.

Anyhow I will keep this thread open till I have tested the compile workflow.
Thank you so much for your concern!

**Comment by nnkhoa** [comment]
Hi, 

I just need some clarification regarding the command line version.
If I want to add 1 specific type of noise to images, all I need to do is set all other noise variables to false, right? I know this is a silly question, but I just want to make sure.

**Comment by BorisMansencal** [comment]
Indeed, to apply only one specific effect E1, you have to set `do_E1=true` and `do_E2=false` for E2!=E1 in *software/DocCreator/src/Degradator/main.cpp*
