### ISSUE TITLE
Generate Chinese document?

### ISSUE THREAD

**Issue by WeihongM** [DocCreator/DocCreator#9]
Hello,
Can this project generate Chinese document? (Use the fonts defined by myself)

**Comment by BorisMansencal** [comment]
Hello,

DocCreator actually consists of two parts:
- 1) create document images from scratch (using a specific background image, text and font)
- 2) add degradation effects to the images of existing documents

The first part, document image generation, is currently not usable for Chinese documents.
I think it would take two things to make it usable:
- change the code that writes the text (from a font). Indeed, for the moment, we only write from left to right, from top to bottom.
- extract a new font for Chinese characters.
The fonts in DocCreator are "bitmap" fonts. Each character is associated with one or more images of this character. The character is not drawn from curves as in a TrueType font. Having different images for a given character allows us to reproduce the diversity of characters found in old documents.
There is a tool in DocCreator to manually extract such a new font.

The second part, adding degradation effects to the images of existing documents, can be used on any image, including images of Chinese documents.

I understand that you are more interested in the first part. What type of documents do you want to generate? If you provide us with an example, we may be able to assess the amount of work required (and the code that needs to be changed).

**Comment by WeihongM** [comment]
Hello, thanks for your reply.
I found your code is all written in C++ format, maybe it is not easy for me to adapt to.
